backup:
  enabled: true
  interval: 60
  compression-level: 9
  retention:
    days: 7
    keep-minimum: 5
  auto-backup:
    on-guild-create: true
    on-guild-delete: true
    on-server-shutdown: true
cleanup-interval-days: 30
last-cleanup: 0
