guild-levels:
  1:
    max-claims: 5
    exp-required: 0
    perks:
      member-limit: 5
      teleport-cooldown: 300
      exp-multiplier: 1.0
      keep-inventory: false
      home-limit: 1
  2:
    max-claims: 10
    exp-required: 1000
    perks:
      member-limit: 8
      teleport-cooldown: 240
      exp-multiplier: 1.2
      keep-inventory: false
      home-limit: 2
  3:
    max-claims: 15
    exp-required: 2500
    perks:
      member-limit: 10
      teleport-cooldown: 180
      exp-multiplier: 1.5
      keep-inventory: true
      home-limit: 3
guild-buffs:
  strength:
    name: "Strength Buff"
    effect: INCREASE_DAMAGE
    level: 1
    cost: 1000
    duration: 3600
    permission: "guild.buff.strength"
  speed:
    name: "Speed Buff"
    effect: SPEED
    level: 2
    cost: 2000
    duration: 3600
    permission: "guild.buff.speed"
  haste:
    name: "Haste Buff"
    effect: FAST_DIGGING
    level: 1
    cost: 1500
    duration: 3600
    permission: "guild.buff.haste"

exp-sources:
  blocks:
    enabled: true
    values:
      DIAMOND_ORE: 10
      ANCIENT_DEBRIS: 20
      DEFAULT: 1
  
  vanilla-mobs:
    enabled: true
    values:
      ENDER_DRAGON: 1000
      WITHER: 500
      DEFAULT: 5
  
  mythicmobs:
    enabled: true
    mobs:
      sewerslime: 50  # Direct mob ID mapping
    multipliers:
      Legendary: 100
      Elite: 50
      Boss: 25
      DEFAULT: 10

storage:
  type: YAML  # or SQL
  mysql:
    host: localhost
    port: 3306
    database: guilds
    username: root
    password: password
events:
  territory-control:
    rewards:
      first-place:
        - "money 15000"
        - "mythic:TerritoryKey"
        - "command eco addbal %player% 1000"
      second-place:
        - "money 10000"
        - "mythic:CommonKey"
      third-place:
        - "money 5000"

  pvp-tournament:
    rewards:
      first-place:
        - "money 20000"
        - "mythic:PvPChampionSword"
        - "command broadcast &6%player% is the PvP Champion!"
      second-place:
        - "money 12000"
        - "mythic:GladiatorArmor"
      third-place:
        - "money 8000"
        - "mythic:WarriorKey"

  resource-race:
    rewards:
      first-place:
        - "money 25000"
        - "mythic:MinerPickaxe"
        - "command give %player% diamond_block 64"
      second-place:
        - "money 15000"
        - "mythic:MinerKey"
      third-place:
        - "money 10000"
        - "command give %player% diamond 32"

  boss-raid:
    boss-type: "mythic:GuildBoss" # Use format "mythic:MobName" for MythicMobs or vanilla entity type
    spawn-location:
      world: "world"
      x: 0
      y: 80
      z: 0
    rewards:
      first-place:
        - "mythic:LegendaryKey"
        - "money 10000"
      second-place:
        - "mythic:RareKey"
        - "money 5000"
      third-place:
        - "mythic:CommonKey"
        - "money 2500"



event-schedule:
  territory-control:
    time: "12:00"
    days: [MONDAY, WEDNESDAY, FRIDAY]
    duration: 60 # minutes
    min-players: 10
    announce-before: [30, 15, 5] # minutes

  pvp-tournament:
    time: "18:00"
    days: [TUESDAY, THURSDAY]
    duration: 45
    min-players: 8
    announce-before: [30, 15, 5]

  resource-race:
    time: "15:00"
    days: [SATURDAY]
    duration: 30
    min-players: 6
    announce-before: [15, 5]

  boss-raid:
    time: "20:00"
    days: [SUNDAY]
    duration: 90
    min-players: 12
    announce-before: [60, 30, 15, 5]

backup:
  enabled: true
  interval: 60 # minutes
  compression-level: 9 # 1-9, higher = better compression but slower
  retention:
    days: 7
    keep-minimum: 5 # minimum backups to keep regardless of age
  auto-backup:
    on-guild-create: true
    on-guild-delete: true
    on-server-shutdown: true