# Core Guild Settings
# Storage Settings
storage:
  type: YAML  # Change to SQL if you want to use SQL storage
  mysql:
    host: localhost
    port: 3306
    database: guilds
    username: root
    password: password
  #guild storage chest settings
  settings: 
    default-rows: 1
    save-interval: 300  # seconds
    transaction-logging: true

guild-levels:
  1:
    max-claims: 5
    exp-required: 0
    perks:
      member-limit: 5
      teleport-cooldown: 300
      exp-multiplier: 1.0
      keep-inventory: false
      home-limit: 1
      storage-rows: 1  # 1 row (9 slots)
      storage-access: true
  2:
    max-claims: 10
    exp-required: 1000
    perks:
      member-limit: 8
      teleport-cooldown: 240
      exp-multiplier: 1.2
      keep-inventory: false
      home-limit: 2
      storage-rows: 2  # 2 rows (18 slots)
  3:
    max-claims: 15
    exp-required: 2500
    perks:
      member-limit: 10
      teleport-cooldown: 180
      exp-multiplier: 1.5
      keep-inventory: true
      home-limit: 3
      storage-rows: 3  # 3 rows (27 slots)

guild-claims:
  protection:
    block-break: true
    block-place: true
    interact: true
    containers: true
    entity-damage: true
    redstone: true
    pistons: true
    explosions: true
  flags:
    allow-allies: false
    mob-spawning: true
    pvp: false
    fire-spread: false

# Experience System
exp-sources:
  blocks:
    enabled: true
    values:
      DIAMOND_ORE: 10
      ANCIENT_DEBRIS: 20
      DEFAULT: 1
  vanilla-mobs:
    enabled: true
    values:
      ENDER_DRAGON: 1000
      WITHER: 500
      DEFAULT: 5
    mythicmobs:
      enabled: true
      values:
        sewerslime: 50
        # Add any other mythicmob types and their exp values here
      multipliers:
        Legendary: 100
        Elite: 50
        Boss: 25
        DEFAULT: 10

guild-settings:
  allow-structures: true
  allow-friendly-fire: false  # Whether guild members can PvP each other in guild territory

# Enable or disable configuration validation
validate-config: false


advanced:
  custom-model-data:
    enabled: false  # Disabled by default
    fallback-materials:  # Regular items used when disabled
      members: PLAYER_HEAD
      claims: MAP
      settings: COMPARATOR
      storage: ENDER_CHEST
      claimed-chunk: EMERALD_BLOCK
      unclaimed-chunk: GRAY_STAINED_GLASS_PANE
      back: ARROW

# Events configuration moved to events.yml
