# Core Guild Settings
# Storage Settings
storage:
  type: YAML
  mysql:
    host: localhost
    port: 3306
    database: guilds
    username: root
    password: password
  #guild storage chest settings
  settings: 
    default-rows: 1
    save-interval: 300  # seconds
    transaction-logging: true

guild-levels:
  1:
    max-claims: 5
    exp-required: 0
    perks:
      member-limit: 5
      teleport-cooldown: 300
      exp-multiplier: 1.0
      keep-inventory: false
      home-limit: 1
      storage-rows: 1  # 1 row (9 slots)
      storage-access: true
  2:
    max-claims: 10
    exp-required: 1000
    perks:
      member-limit: 8
      teleport-cooldown: 240
      exp-multiplier: 1.2
      keep-inventory: false
      home-limit: 2
      storage-rows: 2  # 2 rows (18 slots)
  3:
    max-claims: 15
    exp-required: 2500
    perks:
      member-limit: 10
      teleport-cooldown: 180
      exp-multiplier: 1.5
      keep-inventory: true
      home-limit: 3
      storage-rows: 3  # 3 rows (27 slots)




# Guild Buffs

guild-buffs:
  strength:
    name: "Warrior's Might"
    type: BOTH
    effect: INCREASE_DAMAGE
    stat-type: PHYSICAL_DAMAGE
    stat-value: 5.0
    cost: 1000
    level: 1
    duration: 3600
    permission: "guild.buff.strength"
    slot: 0
    material: DIAMOND_SWORD

  defense:
    name: "Guardian's Shield"
    type: STAT
    stat-type: DEFENSE
    stat-value: 10.0
    cost: 1500
    duration: 3600
    permission: "guild.buff.defense"
    slot: 1
    material: SHIELD

  speed:
    name: "Swift Movement"
    type: POTION
    effect: SPEED
    level: 2
    cost: 800
    duration: 1800
    permission: "guild.buff.speed"
    slot: 2
    material: FEATHER

  critical:
    name: "Critical Master"
    type: STAT
    stat-type: "CRITICAL_STRIKE_CHANCE"
    stat-value: 15.0
    level: 1
    cost: 2000
    duration: 3600
    slot: 3
    material: DIAMOND_AXE

  tank:
    name: "Tank's Blessing"
    type: STAT
    stat-type: "ARMOR_GENERIC"
    stat-value: 20.0
    level: 1
    cost: 1500
    duration: 1800
    slot: 4
    material: DIAMOND_CHESTPLATE

  lifesteal:
    name: "Vampiric Aura"
    type: STAT
    stat-type: "LIFESTEAL_POWER"
    stat-value: 0.15
    level: 1
    cost: 2500
    duration: 1200
    slot: 5
    material: REDSTONE
# Territory Protection
guild-claims:
  protection:
    block-break: true
    block-place: true
    interact: true
    containers: true
    entity-damage: true
    redstone: true
    pistons: true
    explosions: true
  flags:
    allow-allies: false
    mob-spawning: true
    pvp: false
    fire-spread: false

# Experience System
exp-sources:
  blocks:
    enabled: true
    values:
      DIAMOND_ORE: 10
      ANCIENT_DEBRIS: 20
      DEFAULT: 1
  vanilla-mobs:
    enabled: true
    values:
      ENDER_DRAGON: 1000
      WITHER: 500
      DEFAULT: 5
    mythicmobs:
      enabled: true
      values:
        sewerslime: 50
        # Add any other mythicmob types and their exp values here
      multipliers:
        Legendary: 100
        Elite: 50
        Boss: 25
        DEFAULT: 10

# Guild Events
events:
  territory-control:
    enabled: true
    rewards:
      first-place:
        - "money 15000"
        - "mythic:TerritoryKey"
        - "claims 5"
      second-place:
        - "money 10000"
        - "claims 3"
      third-place:
        - "money 5000"
        - "claims 1"
  pvp-tournament:
    enabled: true
    rewards:
      first-place:
        - "money 20000"
      second-place:
        - "money 12000"
        - "mythic:GladiatorArmor"
      third-place:
        - "money 8000"
        - "mythic:WarriorKey"
  resource-race:
    enabled: true
    rewards:
      first-place:
        - "money 25000"
      second-place:
        - "money 15000"
        - "mythic:MinerKey"
      third-place:
        - "money 10000"
        - "command give %player% diamond 32"
  boss-raid:
    enabled: true
    boss-type: "mythic:GuildBoss"
    spawn-location:
      world: "world"
      x: 0
      y: 80
      z: 0
    rewards:
      first-place:
        - "mythic:LegendaryKey"
        - "money 10000"
      second-place:
        - "mythic:RareKey"
        - "money 5000"
      third-place:
        - "mythic:CommonKey"
        - "money 2500"
# Event Schedule
event-schedule:
  territory-control:
    time: "12:00"
    days: [MONDAY, WEDNESDAY, FRIDAY]
    duration: 60
    min-players: 10
    announce-before: [30, 15, 5]
  pvp-tournament:
    time: "18:00"
    days: [TUESDAY, THURSDAY]
    duration: 45
    min-players: 8
    announce-before: [30, 15, 5]
  resource-race:
    time: "15:00"
    days: [SATURDAY]
    duration: 30
    min-players: 6
    announce-before: [15, 5]
  boss-raid:
    time: "20:00"
    days: [SUNDAY]
    duration: 90
    min-players: 12
    announce-before: [60, 30, 15, 5]



# Backup Settings
backup:
  enabled: true
  interval: 60
  compression-level: 9
  retention:
    days: 7
    keep-minimum: 5
  auto-backup:
    on-guild-create: true
    on-guild-delete: true
    on-server-shutdown: true
