# Core Guild Settings
guild-levels:
  1:
    max-claims: 5
    exp-required: 0
    perks:
      member-limit: 5
      teleport-cooldown: 300
      exp-multiplier: 1.0
      keep-inventory: false
      home-limit: 1
  2:
    max-claims: 10
    exp-required: 1000
    perks:
      member-limit: 8
      teleport-cooldown: 240
      exp-multiplier: 1.2
      keep-inventory: false
      home-limit: 2
  3:
    max-claims: 15
    exp-required: 2500
    perks:
      member-limit: 10
      teleport-cooldown: 180
      exp-multiplier: 1.5
      keep-inventory: true
      home-limit: 3

# Territory Protection
guild-claims:
  protection:
    block-break: true
    block-place: true
    interact: true
    containers: true
    entity-damage: true
    redstone: true
    pistons: true
    explosions: true
  flags:
    allow-allies: false
    mob-spawning: true
    pvp: false
    fire-spread: false

# Experience System
exp-sources:
  blocks:
    enabled: true
    values:
      DIAMOND_ORE: 10
      ANCIENT_DEBRIS: 20
      DEFAULT: 1
  vanilla-mobs:
    enabled: true
    values:
      ENDER_DRAGON: 1000
      WITHER: 500
      DEFAULT: 5
  mythicmobs:
    enabled: true
    mobs:
      sewerslime: 50
    multipliers:
      Legendary: 100
      Elite: 50
      Boss: 25
      DEFAULT: 10

# Guild Events
events:
  territory-control:
    rewards:
      first-place:
        - "money 15000"
        - "mythic:TerritoryKey"
        - "command eco addbal %player% 1000"
      second-place:
        - "money 10000"
        - "mythic:CommonKey"
      third-place:
        - "money 5000"
  pvp-tournament:
    rewards:
      first-place:
        - "money 20000"
        - "mythic:PvPChampionSword"
        - "command broadcast &6%player% is the PvP Champion!"
      second-place:
        - "money 12000"
        - "mythic:GladiatorArmor"
      third-place:
        - "money 8000"
        - "mythic:WarriorKey"
  resource-race:
    rewards:
      first-place:
        - "money 25000"
        - "mythic:MinerPickaxe"
        - "command give %player% diamond_block 64"
      second-place:
        - "money 15000"
        - "mythic:MinerKey"
      third-place:
        - "money 10000"
        - "command give %player% diamond 32"
  boss-raid:
    boss-type: "mythic:GuildBoss"
    spawn-location:
      world: "world"
      x: 0
      y: 80
      z: 0
    rewards:
      first-place:
        - "mythic:LegendaryKey"
        - "money 10000"
      second-place:
        - "mythic:RareKey"
        - "money 5000"
      third-place:
        - "mythic:CommonKey"
        - "money 2500"

# Event Schedule
event-schedule:
  territory-control:
    time: "12:00"
    days: [MONDAY, WEDNESDAY, FRIDAY]
    duration: 60
    min-players: 10
    announce-before: [30, 15, 5]
  pvp-tournament:
    time: "18:00"
    days: [TUESDAY, THURSDAY]
    duration: 45
    min-players: 8
    announce-before: [30, 15, 5]
  resource-race:
    time: "15:00"
    days: [SATURDAY]
    duration: 30
    min-players: 6
    announce-before: [15, 5]
  boss-raid:
    time: "20:00"
    days: [SUNDAY]
    duration: 90
    min-players: 12
    announce-before: [60, 30, 15, 5]

# Storage Settings
storage:
  type: YAML
  mysql:
    host: localhost
    port: 3306
    database: guilds
    username: root
    password: password

# Backup Settings
backup:
  enabled: true
  interval: 60
  compression-level: 9
  retention:
    days: 7
    keep-minimum: 5
  auto-backup:
    on-guild-create: true
    on-guild-delete: true
    on-server-shutdown: true
