name: PwingGuilds
version: '${version}'
main: com.pwing.guilds.PwingGuilds
api-version: '1.20'
description: A comprehensive guild system plugin
authors: [finder17]
depend: [Vault]
softdepend: [WorldGuard, PlaceholderAPI, MythicMobs, Skript, ViaVersion]

commands:
  guild:
    description: Main guild command
    aliases: [g]
  guildadmin:
    description: Guild admin commands
    aliases: [ga]
  alliance:
    description: Alliance management commands
    aliases: [ally]

permissions:
  guilds.command.guild:
    description: Allows use of guild commands
    default: true
  guilds.admin:
    description: Allows use of guild admin commands
    default: op
  guild.*:
    default: op
    description: All guild permissions
    children:
      guild.use: true
      guild.admin: true
      guild.alliance: true
  guild.use:
    default: true  # This makes basic guild commands available to everyone
    description: Allows using basic guild commands
  guild.alliance:
    default: true  # This makes basic alliance commands available to everyone
    description: Access to alliance commands
  pwingguilds.migrate:
    description: Allows the user to migrate data storage
    default: op
